name: CodeQuality
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format


  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ty (type checker)
        run: pip install ty
      # - run: pwd
      - name: check code
        run: ty check
      - run: ls -l
